import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NetworkStatusProvider from "@/utils/NetworkStatusProvider";
import Layout from "@/utils/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" reverseOrder={false} />
        <NetworkStatusProvider>
          <Layout>{children}</Layout>
        </NetworkStatusProvider>
      </body>
    </html>
  );
}
